<?php

return [
    [
        'country' => 'Cambodia',
        'city' => 'Cambodia Office',
        'flag' => '🇰🇭',
        'badge' => null,
        'address' => "Krousar Thmey Cambodia\n#145 street 132, Toeuk Laâk I, Toul Kork\nPhnom Penh - PO Box 1393",
        'phone' => '+855 (0)23 880 502',
        'email' => 'communication@krousar-thmey.org',
        'accent_color' => 'border-[#2d6fa3]',
        'badge_color' => 'bg-[#2d6fa3] text-white',
    ],
    [
        'country' => 'France',
        'city' => 'Krousar Thmey France',
        'flag' => '🇫🇷',
        'badge' => null,
        'address' => "Krousar Thmey France\n62 rue Greneta\n75002 Paris",
        'phone' => '01 40 13 06 30',
        'email' => 'france@krousar-thmey.org',
        'accent_color' => 'border-[#2d6fa3]',
        'badge_color' => 'bg-[#2d6fa3] text-white',
    ],
    [
        'country' => 'Singapore',
        'city' => 'Krousar Thmey Singapore',
        'flag' => '🇸🇬',
        'badge' => null,
        'address' => "Krousar Thmey Singapore\n29 Leonie Hill, Horizon Towers West\nApt 13-04\nSingapore",
        'phone' => '+65 98 506 438',
        'email' => 'singapore@krousar-thmey.org',
        'accent_color' => 'border-[#2d6fa3]',
        'badge_color' => 'bg-[#2d6fa3] text-white',
    ],
    [
        'country' => 'Switzerland',
        'city' => 'Krousar Thmey Switzerland',
        'flag' => '🇨🇭',
        'badge' => null,
        'address' => "Krousar Thmey Switzerland\nc/o Mme Sylvie Bédat\nRoute de Florissant 89 A\n1206 Geneva",
        'phone' => '+41 79 203 70 82',
        'email' => 'switzerland@krousar-thmey.org',
        'accent_color' => 'border-[#2d6fa3]',
        'badge_color' => 'bg-[#2d6fa3] text-white',
    ],
];
